name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        ACCESS_TOKEN_SECRET : ${{ secrets.ACCESS_TOKEN_SECRET }}
        DB_HOST : ${{ secrets.DB_HOST }}
        DB_NAME : ${{ secrets.DB_NAME }}
        DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
        DB_USER : ${{ secrets.DB_USER }}
        CONTACT_EMAIL : ${{ secrets.CONTACT_EMAIL }}
        CONTACT_SERVICE_EMAIL : ${{ secrets.CONTACT_SERVICE_EMAIL }}
        VERIFY_EMAIL : ${{ secrets.VERIFY_EMAIL }}
        EMAIL_HOST : ${{ secrets.EMAIL_HOST }}
        EMAIL_PASS : ${{ secrets.EMAIL_PASS }}
        EMAIL_PORT : ${{ secrets.EMAIL_PORT }}
        EMAIL_SECURE : ${{ secrets.EMAIL_SECURE }}
        EMAIL_USER : ${{ secrets.EMAIL_USER }}
        REFRESH_TOKEN_SECRET : ${{ secrets.REFRESH_TOKEN_SECRET }}
        RAZORPAY_KEY_SECRET  :  ${{ secrets.RAZORPAY_KEY_SECRET }}
        AWS_ACCESS_KEY_ID_ : ${{ secrets.AWS_ACCESS_KEY_ID_ }}
        AWS_SECRET_ACCESS_KEY_ : ${{ secrets.AWS_SECRET_ACCESS_KEY_ }}
        AWS_REGION_ : ${{ secrets.AWS_REGION_ }}
        S3_BUCKET_NAME_ : ${{ secrets.S3_BUCKET_NAME_ }}
        SHIPROCKET_REFRESH_TOKEN  :  ${{ secrets.SHIPROCKET_REFRESH_TOKEN }}
        BUCKET_URL : ${{ vars.BUCKET_URL }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}